ERROR 2025-07-05 21:33:10,345 log 4700 14808 Internal Server Error: /feed/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 71, in feed
    user_profile = request.user.userprofile
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\fields\related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
    ...<2 lines>...
    )
django.contrib.auth.models.User.userprofile.RelatedObjectDoesNotExist: User has no userprofile.
ERROR 2025-07-05 21:35:32,174 log 4700 14808 Internal Server Error: /feed/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 71, in feed
    user_profile = request.user.userprofile
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\fields\related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
    ...<2 lines>...
    )
django.contrib.auth.models.User.userprofile.RelatedObjectDoesNotExist: User has no userprofile.
ERROR 2025-07-05 21:45:07,267 log 5024 11308 Internal Server Error: /thought/create/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 129, in create_thought
    return render(request, 'thoughtify/create_thought.html', {'form': form})
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: thoughtify/create_thought.html
ERROR 2025-07-05 22:02:36,415 log 6412 12156 Internal Server Error: /admin/thoughtify/thought/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'author_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: Thought has no field named 'author_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\utils.py", line 281, in lookup_field
    value = attr(obj)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\admin.py", line 34, in author_code
    return obj.author.userprofile.anonymous_code
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'userprofile'
ERROR 2025-07-05 22:03:37,249 log 6412 7880 Internal Server Error: /admin/thoughtify/thought/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'author_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: Thought has no field named 'author_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\admin\utils.py", line 281, in lookup_field
    value = attr(obj)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\admin.py", line 34, in author_code
    return obj.author.userprofile.anonymous_code
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'userprofile'
ERROR 2025-07-05 22:09:58,848 log 3216 11560 Internal Server Error: /feed/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 71, in feed
    user_profile = request.user.userprofile
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\fields\related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
    ...<2 lines>...
    )
django.contrib.auth.models.User.userprofile.RelatedObjectDoesNotExist: User has no userprofile.
ERROR 2025-07-05 22:14:11,088 log 3216 11560 Internal Server Error: /feed/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 71, in feed
    user_profile = request.user.userprofile
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\fields\related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
    ...<2 lines>...
    )
django.contrib.auth.models.User.userprofile.RelatedObjectDoesNotExist: User has no userprofile.
ERROR 2025-07-05 22:14:13,122 log 3216 11560 Internal Server Error: /feed/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 71, in feed
    user_profile = request.user.userprofile
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\fields\related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
    ...<2 lines>...
    )
django.contrib.auth.models.User.userprofile.RelatedObjectDoesNotExist: User has no userprofile.
ERROR 2025-07-05 22:14:22,928 log 3216 11560 Internal Server Error: /feed/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 71, in feed
    user_profile = request.user.userprofile
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\fields\related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
    ...<2 lines>...
    )
django.contrib.auth.models.User.userprofile.RelatedObjectDoesNotExist: User has no userprofile.
ERROR 2025-07-05 22:17:52,544 log 3216 9396 Internal Server Error: /thought/85/update/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 150, in update_thought
    return render(request, 'thoughtify/update_thought.html', {
        'form': form,
        'thought': thought
    })
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: thoughtify/update_thought.html
ERROR 2025-07-09 20:31:46,248 log 4752 12276 Internal Server Error: /feed/
Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 96, in feed
    return render(request, 'thoughtify/feed.html', {
        'thoughts': thoughts_page,
        'emotion_tags': emotion_tags,
        'show_daily_nudge': show_daily_nudge
    })
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 211: 'endblock'. Did you forget to register or load this tag?
ERROR 2025-07-09 20:32:03,119 log 4752 12276 Internal Server Error: /feed/
Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 96, in feed
    return render(request, 'thoughtify/feed.html', {
        'thoughts': thoughts_page,
        'emotion_tags': emotion_tags,
        'show_daily_nudge': show_daily_nudge
    })
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
    ...<3 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 211: 'endblock'. Did you forget to register or load this tag?
ERROR 2025-07-09 22:59:27,792 log 4752 8180 Internal Server Error: /thought/86/update/
Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 150, in update_thought
    return render(request, 'thoughtify/update_thought.html', {
        'form': form,
        'thought': thought
    })
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: thoughtify/update_thought.html
ERROR 2025-07-09 23:32:30,009 log 9868 12608 Internal Server Error: /signup/
Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 67, in signup_view
    return render(request, 'thoughtify/signup.html', {'form': form})
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\defaulttags.py", line 960, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\defaulttags.py", line 859, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'split'
ERROR 2025-07-09 23:32:48,479 log 9868 12608 Internal Server Error: /signup/
Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 67, in signup_view
    return render(request, 'thoughtify/signup.html', {'form': form})
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\defaulttags.py", line 960, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\defaulttags.py", line 859, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'split'
ERROR 2025-07-09 23:35:29,213 log 9868 12608 Internal Server Error: /signup/
Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 67, in signup_view
    return render(request, 'thoughtify/signup.html', {'form': form})
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\defaulttags.py", line 960, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\defaulttags.py", line 859, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'split'
ERROR 2025-07-15 22:31:17,887 log 4900 1032 Internal Server Error: /admin/auth/user/
Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'get_anonymous_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 289, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 322, in _get_non_gfk_field
    field = opts.get_field(name)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
        "%s has no field named '%s'" % (self.object_name, field_name)
    )
django.core.exceptions.FieldDoesNotExist: User has no field named 'get_anonymous_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 505, in __get__
    rel_obj = self.related.get_cached_value(instance)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\fields\mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'userprofile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: thoughtify_userprofile.email_confirmed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 343, in result_list
    "results": list(results(cl)),
               ~~~~^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 319, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 310, in __init__
    super().__init__(*items)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 217, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 298, in lookup_field
    value = attr(obj)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\admin.py", line 17, in get_anonymous_code
    return obj.userprofile.anonymous_code
           ^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 513, in __get__
    rel_obj = self.get_queryset(instance=instance).get(**filter_args)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: thoughtify_userprofile.email_confirmed
ERROR 2025-07-16 19:05:13,821 log 15032 11368 Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\fields\related_descriptors.py", line 473, in __get__
    rel_obj = self.related.get_cached_value(instance)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\fields\mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'userprofile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: thoughtify_userprofile.email_confirmed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 237, in profile_view
    profile = user.userprofile
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\fields\related_descriptors.py", line 481, in __get__
    rel_obj = self.get_queryset(instance=instance).get(**filter_args)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: thoughtify_userprofile.email_confirmed
ERROR 2025-07-16 19:38:44,753 log 13208 3924 Internal Server Error: /my-thoughts/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 100, in my_thoughts_view
    return render(request, 'thoughtify/my_thoughts.html', {
        'thoughts': thoughts_page,
        'user_profile': user_profile,
    })
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Admin\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: thoughtify/my_thoughts.html
ERROR 2025-07-26 20:01:02,026 log 8604 5624 Internal Server Error: /profile/
Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 206, in profile_view
    'profile_picture': profile.profile_picture.url if profile.profile_picture else None,
                                                      ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserProfile' object has no attribute 'profile_picture'
ERROR 2025-07-26 20:11:19,291 log 14880 1948 Internal Server Error: /profile/
Traceback (most recent call last):
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\TEJASWI\my projects\projects\django project\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\TEJASWI\my projects\projects\django project\anonymous_thought_board\thoughtify\views.py", line 207, in profile_view
    'profile_picture': profile.profile_picture.url if profile.profile_picture else None,
                                                      ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserProfile' object has no attribute 'profile_picture'
